esphome:
  name: sonoff_02_fan
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret SH158_wifi
  password: !secret SH158_wifi_password
  manual_ip:
    static_ip: 192.168.1.36
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
sensor:
  - platform: wifi_signal
    name: esphome_sonoff02_wifi_signal
    update_interval: 10s
  - platform: uptime
    name: esphome_sonoff02_uptime
  - platform: adc
    pin: VCC
    name: esphome_sonoff02_VCC_Voltage
    
text_sensor:
  - platform: version
    name: esphome_sonoff02_esphome_version

status_led:
  pin:
    number: GPIO13
    inverted: no
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 2 Fan Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: restart
    name: esphome_sonoff02_restart
  - platform: gpio
    name: "Fan"
    pin: GPIO12
    id: relay
